// ADOC Settings
// enables syntax highlighting:
:source-highlighter: rouge

// Variables
:conda_env_name: rp
:python_version: 3.8

= Predicting Future Sales

== 📈 Introduction

The goal of this research project was to utilize the "Future Sales" dataset from the Kaggle competition https://www.kaggle.com/c/competitive-data-science-predict-future-sales[Predict Future Sales].
This was used to predict the sales of the upcoming months from individual items across selected branches spread across the country.

The data consists of 2'935'849 records of individual sales from different items, span across 2.5 years (33 months to be precise, these are referenced as `date_block_num` in the project), from a Russian software firm https://1c.ru/eng/title.htm[1C Company].
The task implied to obtain a grasp of the data by performing an EDA and using the newly gained insights to craft new features.
The data consists of not only the items, shops and the sales itself, but also the name of the shops which includes the cities name, the item price as well as its category.

With the newly crafted feature engineered data, it was then applied to different linear regression models, which are well suited to solve this problem.
Additionally, we also inspected the impact of a time series analysis along the way.
The models were then further examined with various data manipulation techniques such as scaling or different encoding of categorical features.

To proceed, comparisons were made originating observations from the EDA such as dropping certain outliers and removing shops which are considered in the training set, but not in the final testing data.
Finally, different hyperparameters and regressive models were compared using cross validation to compare varying impacts on performance.

== 🛠 Set-Up

The environment is managed with https://anaconda.org[conda] and was built on python {python_version}.

The packages are managed using https://python-poetry.org[poetry].

To get started, https://docs.conda.io/projects/continuumio-conda/en/latest/user-guide/install/index.html#system-requirements[install conda] and create a new environment and activate it using following code:
[subs="+attributes"]
```
conda create --name {conda_env_name} python={python_version}
conda activate {conda_env_name}
```

Then, begin by installing `poetry`:
```
conda install poetry
```

Finally, navigate to the GitHub repository root folder, then execute following line to install all packages:
```
poetry install
```

== ⚠️ Troubleshooting


=== Issues on Apple Silicon (M1)

+++ <details><summary> +++
Expand to view patches applied on an Apple Silicon machine.
+++ </summary><div> +++

Some issues were encountered after setting up the conda environment
with poetry. Following fixes were applied

First, check that the right conda environment is active

[subs="+attributes"]
```
conda activate {conda_env_name}
```

==== Issues with `XGBoost`

===== Issue: *XGBoost Library (libxgboost.dylib) could not be loaded.*

```
conda install -c conda-forge py-xgboost
```


===== Issue: *cannot import name 'CUDF_concat' from 'xgboost.compat'*

```
brew install xgboost
```
+++ <br></div></details> +++

=== Issues on Ubuntu

+++ <details><summary> +++
Expand to view patches applied on an Ubuntu machine.
+++ </summary><div> +++

First, check that the right conda environment is active

[subs="+attributes"]
```
conda activate {conda_env_name}
```

==== Issues with connecting to the debugger using PyCharm (Professional) IDE

Had issues to get the debugger to run using PyCharm. Not entirely sure which exact package is missing.
Rerunning following command did alleviate the issue. Still encountered some very strange bugs along the way
after coming back from coding in a Mac environment after a prolonged period of time.
```sh
conda install jupyter
```

Additionally, I did reset all the settings / caches on an IDE and project level. IDE directories are mentioned https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs[here],
the project level configs are found in the `.idea/` folder in the project root.

+++ <br></div></details> +++
