// ADOC Settings
// enables syntax highlighting:
:source-highlighter: rouge

// Variables
:miro_link: https://miro.com/app/board/o9J_lNamDng=/
:conda_env_name: rp
:python_version: 3.8

= Predicting Future Sales

== 📈 Introduction

Repo for my 5th semester research project

== 📝 Planing

Planing is done on a miro board: {miro_link}


== 🛠 Set-Up

The environment is managed with https://anaconda.org[conda] and was built on python {python_version}.

The packages are managed using https://python-poetry.org[poetry].

To get started, https://docs.conda.io/projects/continuumio-conda/en/latest/user-guide/install/index.html#system-requirements[install conda] and create a new environment and activate it using following code:
[subs="+attributes"]
```
conda create --name {conda_env_name} python={python_version}
conda activate {conda_env_name}
```

Then, begin by installing `poetry`:
```
conda install poetry
```

Finally, navigate to the GitHub repository root folder, then execute following line to install all packages:
```
poetry install
```

== ⚠️ Troubleshooting


=== Issues on Apple Silicon (M1)

+++ <details><summary> +++
Expand to view patches applied on an Apple Silicon machine.
+++ </summary><div> +++

Some issues were encountered after setting up the conda environment
with poetry. Following fixes were applied

First, check that the right conda environment is active

[subs="+attributes"]
```
conda activate {conda_env_name}
```

==== Issues with `XGBoost`

===== Issue: *XGBoost Library (libxgboost.dylib) could not be loaded.*

```
conda install -c conda-forge py-xgboost
```


===== Issue: *cannot import name 'CUDF_concat' from 'xgboost.compat'*

```
brew install xgboost
```
+++ <br></div></details> +++
