// ADOC Settings
// enables syntax highlighting:
:source-highlighter: rouge

// Variables
:conda_env_name: rp
:python_version: 3.8

= Predicting Future Sales

== 📈 Introduction

The goal of this research project was to utilize the "Future Sales" dataset from the Kaggle competition https://www.kaggle.com/c/competitive-data-science-predict-future-sales[Predict Future Sales].
This was used to predict the sales of the upcoming months from individual items across selected branches spread across the country.

== 𝌞 Contents

=== Research notebooks

- xref:Predicting_Future_Sales.ipynb[Predicting Future Sales]: main notebook, contains the EDA and feature engineering
- xref:In_Depth_EDA.ipynb[In Depth EDA]: concise information from the EDA that would've inflated the main notebook
- xref:Linear_Regression.ipynb[Linear Regression]: evaluation and training of the linear models. Contains the submission to the competition
- xref:ARIMA.ipynb[ARIMA]: evaluation of a forecasting model

=== Data folder

- xref:data/info/[info] folder containing detailed information, provided by the Kaggle competition
- xref:data/technical/[technical] folder containing the train, test and submission template, provided by the Kaggle competition
- xref:data/feature_engineering/[feature_engineering] folder containing additional information, which was researched manually, used for feature engineering
- xref:data/arima/[arima] folder containing data generated in the ARIMA analysis
- xref:data/out/[out] folder to store the serialized output from the feature engineering
- xref:data/submissions/[submissions] folder to store the final submission files to submit to the Kaggle competition

=== Modules

Located in the xref:src/[src] folder, contains additional modules that were used across the different notebooks.

==== xref:src/plotting/[src/plotting]

Contains xref:src/plotting/Defaults.py[default] file to set default styles to maintain a uniform look across the project

==== xref:src/util/[src/util]

- xref:src/util/ConvertingDateValues.py[ConvertingDateValues.py] operations to handle the datetime datatype within a DataFrame
- xref:src/util/ParseDataframe.py[ParseDataframe.py] operations that parses and extracts information within a DataFrame
- xref:src/util/ListActions.py[ListActions.py] special operations on list elements
- xref:src/util/FunctionExecTime.py[FunctionExecTime.py] function that executes and prints the execution time information from a requested function

=== Report

- LaTeX source files and compiled PDF of the final report

=== Technicalities

- xref:.gitignore[`.gitignore`] managing the repository
- xref:poetry.lock[] & xref:pyproject.toml[] to manage the environment and packages for the project

== 🛠 Set-Up

The environment is managed with https://anaconda.org[conda] and was built on python {python_version}.

The packages are managed using https://python-poetry.org[poetry].

To get started, https://docs.conda.io/projects/continuumio-conda/en/latest/user-guide/install/index.html#system-requirements[install conda] and create a new environment and activate it using following code:
[subs="+attributes"]
```
conda create --name {conda_env_name} python={python_version}
conda activate {conda_env_name}
```

Then, begin by installing `poetry`:
```
conda install poetry
```

Finally, navigate to the GitHub repository root folder, then execute following line to install all packages:
```
poetry install
```

== ⚠️ Troubleshooting


=== Issues on Apple Silicon (M1)

+++ <details><summary> +++
Expand to view patches applied on an Apple Silicon machine.
+++ </summary><div> +++

Some issues were encountered after setting up the conda environment
with poetry. Following fixes were applied

First, check that the right conda environment is active

[subs="+attributes"]
```
conda activate {conda_env_name}
```

==== Issues with `XGBoost`

===== Issue: *XGBoost Library (libxgboost.dylib) could not be loaded.*

```
conda install -c conda-forge py-xgboost
```


===== Issue: *cannot import name 'CUDF_concat' from 'xgboost.compat'*

```
brew install xgboost
```
+++ <br></div></details> +++

=== Issues on Ubuntu

+++ <details><summary> +++
Expand to view patches applied on an Ubuntu machine.
+++ </summary><div> +++

First, check that the right conda environment is active

[subs="+attributes"]
```
conda activate {conda_env_name}
```

==== Issues with connecting to the debugger using PyCharm (Professional) IDE

Had issues to get the debugger to run using PyCharm. Not entirely sure which exact package is missing.
Rerunning following command did alleviate the issue. Still encountered some very strange bugs along the way
after coming back from coding in a Mac environment after a prolonged period of time.
```sh
conda install jupyter
```

Additionally, I did reset all the settings / caches on an IDE and project level. IDE directories are mentioned https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs[here],
the project level configs are found in the `.idea/` folder in the project root.

+++ <br></div></details> +++
